### ISSUE TITLE
attempt to add with overflow

### ISSUE THREAD

**Issue by spease** [knsd/tokio-ping#4]
```
thread 'main' panicked at 'attempt to add with overflow', /home/spease/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-ping-0.1.0/src/ping.rs:138:37
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::panicking::panic
             at libcore/panicking.rs:51
  10: tokio_ping::ping::PingChain::send
             at /home/spease/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-ping-0.1.0/src/ping.rs:138
```
I'm guessing this is caused by sending out enough pings that the sequence count overflows.

**Comment by knsd** [comment]
Hi!

Was it a debug build?

**Comment by spease** [comment]
Yes, it was. Perhaps you could do seq_cnt.wrapping_add(1) and note in the API documentation that it wraps around, if it isn't truly inadvertent?
